version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=12345
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/alvaro/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
